//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLQuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATMON
    {
        public int MaDat { get; set; }
        public string TrangThai { get; set; }
        public int MaSP { get; set; }
        public int MaBan { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
